### ISSUE TITLE
Cannot be used in Unity

### ISSUE THREAD

**Issue by LLLaiYoung** [pjessesco/iPad-PLY-scanner#1]
Hello, the file I exported cannot be visualized in Unity. I use the pcx visualization tool. During the process of modifying this problem, I found that I don’t know how to convert the point cloud information into binary_little_endian

**Comment by pjessesco** [comment]
Hi, thanks for reporting the issue.

Currently, the pointcloud is saved in ascii format. IIRC I could visualize exported PLY file in [MeshLab](https://github.com/cnr-isti-vclab/meshlab), and I believe there is a converting feature(ascii <-> big/little endian) in it...

**Comment by LLLaiYoung** [comment]
Thank you for your review and reply. I read the source code of pcx. It reads the body content in binary mode. At present, I have not found out how floating-point numbers are binary in swift.

**Comment by pjessesco** [comment]
Maybe you can try https://github.com/3DBear/PlyImporter or similar converter for unity. 
I'll close the issue since it is not related with this repository.
